### ISSUE TITLE
Partager les taches de support avec PNP

### ISSUE THREAD

**Issue by estellecomment** [betagouv/audioconf#140]
Pour pouvoir répondre au support à plusieurs, et se passer les tickets selon les niveaux de support nécessaires, un software de support comme rocketchat ou chatwoot serait utile. Ou sinon Crisp, c'est payant mais ca fait le job.

Qu'est-ce que PNP utilise deja comme logiciel de tickets de support ?

**Comment by jdauphant** [comment]
Reprise du projet à 100% par beta
