### ISSUE TITLE
Inclure les collectivités dans Audioconf

### ISSUE THREAD

**Issue by JDixmier** [betagouv/audioconf#204]
- Les collectivités sont actuellement exclues d'Audioconf
- Après discussion avec @jdauphant et @Flightan nous avons finalement décidé de les inclure

**Comment by mcalinghee** [comment]
Note pour la production(operation a faire sur tchap-authentification de prod) : 
- [ ] changer la var env : TCHAP_UNAUTHORIZED_HOME_SERVER_LIST
- [ ] redemarrer la prod
