### ISSUE TITLE
[Proposition] Supprimer une phrase qui prête à confusion

### ISSUE THREAD

**Issue by Caroline-lawson** [betagouv/audioconf#225]
Concernant la phrase "AudioConf de Preprod utilise un service d'authentification pour assurer que seuls les agents publics utilisent les services qui leur sont réservés." sur la page "Renseignez le code que vous avez reçu" en Preprod :

Problème 1 : Certains utilisateurs pensent que seuls les agents publics peuvent utiliser AudioConf, et que les prestataires ne peuvent pas rejoindre une AudioConf.

Problème 2 : La phrase n'apporte pas d'information utile, mais provoque des questions que les utilisateurs ne se posaient pas nécessairement. Ils n'ont pas besoin de savoir.

Proposition : Supprimer la phrase.

**Comment by estellecomment** [comment]
C'est deja fait sur develop : https://github.com/tchapgouv/tchap-identite/blob/develop/theme/tchap-otp-login/login/enter-code.ftl#L18
