### ISSUE TITLE
Remplacer “code de validation” par “code d’authentification”

### ISSUE THREAD

**Issue by Caroline-lawson** [betagouv/audioconf#228]
Sur la page d'accueil, point 3, on parle de "code de validation”, alors qu’on veut que les utilisateurs s’authentifient.

Remplacer “code de validation” par “code d’authentification”. 

![image](https://user-images.githubusercontent.com/78041311/176781806-89ef85b5-ee1f-4890-bffc-0fe973018b01.png)

**Comment by estellecomment** [comment]
done
