### ISSUE TITLE
Mentionner Tchap

### ISSUE THREAD

**Issue by Caroline-lawson** [betagouv/audioconf#229]
Page d'accueil, point 3 : on dit que le code va arriver par mail, mais pas par Tchap, donc certains participants ne s’y attendaient pas.

Ajouter "par mail et sur Tchap".

![image](https://user-images.githubusercontent.com/78041311/176783424-1ffab29c-210f-4a24-b061-05fc306654f7.png)

**Comment by celiacheff** [comment]
Je proposer "et/ou" parce que ceux qui ont pas Tchap ne reçoivent pas dessus

**Comment by estellecomment** [comment]
done
